ALTER TABLE payments ADD COLUMN IF NOT EXISTS customer_email VARCHAR(255);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS customer_name VARCHAR(255);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(50);
