server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: discovery-server
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    user:
      name: eureka
      password: ${EUREKA_PASSWORD}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    register-with-eureka: ${EUREKA_PEER_ENABLED:false}
    fetch-registry: ${EUREKA_PEER_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_PEER_URLS:http://${spring.security.user.name}:${spring.security.user.password}@localhost:${server.port}/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
