server:
  port: 8761
  shutdown: graceful

spring:
  application:
    name: discovery-server
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    user:
      name: eureka
      password: ${EUREKA_PASSWORD}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${EUREKA_HOSTNAME:localhost}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
