package com.skbingegalaxy.booking.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.skbingegalaxy.booking.entity.Booking;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.format.DateTimeFormatter;

/**
 * Generates branded PDF invoices for bookings.
 * Uses OpenPDF (LGPL fork of iText 4) for server-side PDF generation.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class InvoicePdfService {

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 18, Font.BOLD, new Color(99, 102, 241));
    private static final Font HEADING_FONT = new Font(Font.HELVETICA, 12, Font.BOLD);
    private static final Font NORMAL_FONT = new Font(Font.HELVETICA, 10, Font.NORMAL);
    private static final Font SMALL_FONT = new Font(Font.HELVETICA, 8, Font.NORMAL, Color.GRAY);
    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("dd MMM yyyy");
    private static final DateTimeFormatter TIME_FMT = DateTimeFormatter.ofPattern("hh:mm a");

    private final BookingService bookingService;

    /**
     * Generate a PDF invoice for the given booking reference.
     *
     * @return byte array containing the PDF document
     */
    public byte[] generateInvoice(String bookingRef) {
        Booking booking = bookingService.getBookingEntityForSystem(bookingRef);
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        try {
            Document doc = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(doc, baos);
            doc.open();

            // Header
            Paragraph brand = new Paragraph("SK Binge Galaxy", TITLE_FONT);
            brand.setAlignment(Element.ALIGN_CENTER);
            doc.add(brand);

            Paragraph subtitle = new Paragraph("Booking Invoice", HEADING_FONT);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            subtitle.setSpacingAfter(20);
            doc.add(subtitle);

            // Booking details table
            PdfPTable details = new PdfPTable(2);
            details.setWidthPercentage(100);
            details.setWidths(new float[]{1, 2});
            details.setSpacingAfter(15);

            addRow(details, "Booking Ref", booking.getBookingRef());
            addRow(details, "Status", booking.getStatus().name());

            if (booking.getCustomerName() != null) {
                addRow(details, "Customer", booking.getCustomerName());
            }
            if (booking.getCustomerEmail() != null) {
                addRow(details, "Email", booking.getCustomerEmail());
            }
            if (booking.getEventType() != null) {
                addRow(details, "Event Type", booking.getEventType().getName());
            }
            if (booking.getBookingDate() != null) {
                addRow(details, "Date", booking.getBookingDate().format(DATE_FMT));
            }
            if (booking.getStartTime() != null) {
                addRow(details, "Time", booking.getStartTime().format(TIME_FMT));
            }
            addRow(details, "Duration", resolveDuration(booking));
            addRow(details, "Guests", String.valueOf(booking.getNumberOfGuests()));

            doc.add(details);

            // Pricing section
            doc.add(new Paragraph("Pricing", HEADING_FONT));
            doc.add(Chunk.NEWLINE);

            PdfPTable pricing = new PdfPTable(2);
            pricing.setWidthPercentage(60);
            pricing.setHorizontalAlignment(Element.ALIGN_LEFT);
            pricing.setSpacingAfter(15);

            addRow(pricing, "Total Amount", formatINR(booking.getTotalAmount()));
            addRow(pricing, "Collected", formatINR(booking.getCollectedAmount()));
            addRow(pricing, "Payment Status",
                    booking.getPaymentStatus() != null ? booking.getPaymentStatus().name() : "PENDING");

            doc.add(pricing);

            // Special notes
            if (booking.getSpecialNotes() != null && !booking.getSpecialNotes().isBlank()) {
                doc.add(new Paragraph("Special Notes", HEADING_FONT));
                doc.add(new Paragraph(sanitize(booking.getSpecialNotes()), NORMAL_FONT));
                doc.add(Chunk.NEWLINE);
            }

            // Footer
            Paragraph footer = new Paragraph(
                    "Generated by SK Binge Galaxy | This is a computer-generated document.",
                    SMALL_FONT);
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(30);
            doc.add(footer);

            doc.close();
        } catch (Exception e) {
            log.error("Failed to generate PDF invoice for booking {}", bookingRef, e);
            throw new IllegalStateException("Failed to generate invoice PDF", e);
        }

        return baos.toByteArray();
    }

    private void addRow(PdfPTable table, String label, String value) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, HEADING_FONT));
        labelCell.setBorder(0);
        labelCell.setPadding(4);
        table.addCell(labelCell);

        PdfPCell valueCell = new PdfPCell(new Phrase(sanitize(value), NORMAL_FONT));
        valueCell.setBorder(0);
        valueCell.setPadding(4);
        table.addCell(valueCell);
    }

    /**
     * Sanitize user-supplied text before inserting into the PDF.
     * Strips control characters and limits length to prevent injection or corrupt documents.
     */
    private String sanitize(String value) {
        if (value == null || value.isBlank()) return "—";
        // Remove control chars except newline/tab, limit length
        String clean = value.replaceAll("[\\p{Cntrl}&&[^\\n\\t]]", "").trim();
        return clean.length() > 500 ? clean.substring(0, 500) + "…" : clean;
    }

    private String formatINR(BigDecimal amount) {
        if (amount == null) return "₹0.00";
        return "₹" + amount.setScale(2, RoundingMode.HALF_UP).toPlainString();
    }

    private String resolveDuration(Booking booking) {
        int minutes = booking.getDurationMinutes() != null
                ? booking.getDurationMinutes()
                : booking.getDurationHours() * 60;
        if (minutes % 60 == 0) return (minutes / 60) + " hour" + (minutes / 60 != 1 ? "s" : "");
        return (minutes / 60) + "h " + (minutes % 60) + "m";
    }
}
