package com.skbingegalaxy.booking.entity;

public enum BookingEventType {
    // Core lifecycle
    CREATED,
    CONFIRMED,
    CANCELLED,
    CHECKED_IN,
    CHECKED_OUT,
    NO_SHOW,
    PAYMENT_UPDATED,
    MODIFIED,
    REINSTATED,
    COMPLETED,
    RESCHEDULED,
    TRANSFERRED,
    // Production-grade timeline milestones (V43)
    SLOT_HELD,
    PAYMENT_INITIATED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    REFUND_INITIATED,
    REFUND_COMPLETED,
    REFUND_FAILED,
    NOTIFICATION_SENT,
    REMINDER_SENT,
    MANUAL_REVIEW_FLAGGED,
    PRICE_OVERRIDE,
    CHECK_IN_REVERTED,
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    // Support console (Item 24)
    CONFIRMATION_RESENT,
    ESCALATED,
    DE_ESCALATED,
    GOODWILL_ISSUED
}
